### PR TITLE
Verify headers in the excel file before using its data

### PR DESCRIPTION
**Pull request by chayawit**
This fixes issue https://github.com/timcu/sas-select/issues/33.

### CODE REVIEW

**Review by timcu — CHANGES_REQUESTED** [review]
I think we can cope if the columns are rearranged in order. We can also cope if additional columns are added. We just can't cope if the column has been renamed or removed so that is all we should test for.

**Comment by chayawit** [comment]
We should check if the new headers contain all old headers? Should I make it case insensitive?

**Comment by timcu** [comment]
We only have to check for things that will break the code. I think case is important. The test should be 
```
if expected not in df:
    raise ValueError("Missing column", expected)
```
Please also change your code to only read spreadsheet once. Reading the entire spreadsheet across the Internet is very slow compared to every other statement and we definitely shouldn't do it twice.

I like that you have put all the column names in a tuple. What would make it even better is to store each column name in a constant and then use the same constant for the pre-check and the sql insert.
```
GROUP_ID = "Group ID"
SAS_CODE = "SAS Code"
...
COLUMN_NAMES = (GROUP_ID, SAS_CODE, ...)
...
cursor.execute(sql, (index, row[GROUP_ID], row[SAS_CODE], ...))
```

**Comment by timcu** [comment]
Replaced by PR #39

**Pull request closed without merging**
