### PR TITLE
Fix searching

### LINKED ISSUE #10: Search by CompanyCode should produce 1 result if exact match
view_products() in __init__.py searches for products using wild cards (%) for company code as the first search. This is fine if there are no exact matches. If there is an exact match, but the company code also matches other products when % are included then user is presented with many search results even when they knew the exact company code. For example, searching on company code 1001 returns 4 results with the exact match last. This is not an issue with brand names

### PR DESCRIPTION
**Pull request by chayawit**
This fixes https://github.com/timcu/sas-select/issues/10.

### CODE REVIEW

**Comment by timcu** [comment]
When creating a branch that will be suitable for a pull request, please branch from upstream/master and don't include commits from past pull requests in this branch. I have rebased this pull request in #23 so that it only included the one commit.  

Regarding the code, the function sql_search_str is not doing much now and is probably not necessary. It was originally designed to prevent sql containing %% for a like expression. However, %% does work, albeit a bit uglier than just a single %.

**Comment by chayawit** [comment]
> Regarding the code, the function sql_search_str is not doing much now and is probably not necessary. It was originally designed to prevent sql containing %% for a like expression. However, %% does work, albeit a bit uglier than just a single %.

Do we have to worry about the case where `form_search_str is None`?

**Comment by chayawit** [comment]
> When creating a branch that will be suitable for a pull request, please branch from upstream/master

Did you mean merge upstream/master to my master and then branch from my master?

I can't find how to branch from upstream/master.

**Comment by timcu** [comment]
When part of a github project where you can't commit directly to upstream, then you should never merge your own changes into your own master branch. Your own master branch should always be a duplicate of the upstream master. Use "git checkout master; git pull upstream master" to bring the upstream master into your master. Then, when you are about to start on a new pull request, create a new branch from the last commit on your master. When finished, push the new branch to your origin, then create the pull request to upstream master. When pull request is accepted you can then "git pull upstream master" again to get it into your master branch.

**Pull request closed without merging**
