### PR TITLE
webscrape gov.au site for excel url, then populate database with new …

### PR DESCRIPTION
**Pull request by ssw2010**
…data

### CODE REVIEW

**Comment by ssw2010** [comment]
Hi @timcu , hope this works (includes webscrapping code)

**Comment by timcu** [comment]
Hi @ssw2010 . Thanks for the pull request. It needs the "requests" library which is not installed by default. If you want to use it then you need to add it to the requirements.txt. Please make this change and commit to the same branch. Then I will pull your changes.

**Comment by timcu** [comment]
Other fixes before I will pull in changes. 
1. Add beautifulsoup4 to requirements.txt
2. All indentation should be a multiple of 4 spaces
3. Code gives an error local variable "msg1" referenced before assignment. Is this the site change you are talking about? You have a "for" loop which can loop zero to many times but your logic on returning msg1 relies on looping exactly once.
4. You don't need to import xlrd as you are not using it. Only pandas is using it.

**Comment by ssw2010** [comment]
Hi Tim,

Thanks for the pick ups, let me look at those. The change that I saw is the
dept of health has changed the file extension from xlsx to xls in the July
file but looks like there were some additional errors I need to work on.

Thanks, Scott

**Comment by timcu** [comment]
Also href now ends in .xls instead of .xlsx so reducing your filter should work in the old and new way

**Comment by timcu** [comment]
This pull request has been closed because it has been superseded by #3 .

**Pull request closed without merging**
